[tool.poetry]
name = "repl_python3_hatelace"
version = "0.1.0"
description = ""
authors = ["3ghin5 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
funcy = "^1.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
